# Generated by Django 4.1.7 on 2023-04-18 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='dataAgendamento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação'),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.estado')),
            ],
        ),
    ]
