# Generated by Django 4.1.7 on 2023-04-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cidade_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=50)),
                ('logo_base64', models.TextField()),
                ('data_cadastro', models.DateField()),
                ('horario_abertura', models.TimeField()),
                ('horario_fechamento', models.TimeField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
    ]
