# Generated by Django 4.1.7 on 2023-04-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo_base64',
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
